version: '2.3'
services:
  bot:
    image: cirno
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    restart: on-failure
    volumes:
      - type: bind
        source: ./Lists/Private
        target: /app/Lists/Private
      # Uncomment the below lines to use your own config file.
      - type: bind
        source: ./config.json
        target: /app/config.json
    environment:
      # Overrides your configs Redis options for use with Docker Compose
      #  I don't advise changing this unless you have a strange setup
      - REDIS_DOCKER_OVERRIDE=true
  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - type: bind
        source: ./data
        target: /data
    command: --appendonly yes
  redis-exposer:
    image: ghcr.io/erisa/redis-exposer
    restart: always
    env_file:
      - .exposer.env
    ports:
      - 127.0.0.1:3000:3000
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable
    restart: always
