name: docker-test-build

on:
  push:
    branches:    
      - '**'        # matches every branch
      - '!main'   # excludes master

  pull_request:
    branches:    
      - '**'        # matches every branch

jobs:
  cliptok-build-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-iteration3-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-iteration3-
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: |
            ghcr.io/erisa/cliptok:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
